---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "in_memory_hub"
  name: "in-memory-hub-svc"
spec:
  ports:
    - name: "port-1-in-mem"
      port: 9000
      protocol: "TCP"
      targetPort: 9000
  selector:
    app: "in_memory_hub"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "jmeter"
  name: "client-svc"
spec:
  ports:
    - name: "client-port"
      port: 9100
      protocol: "TCP"
      targetPort: 9100
  selector:
    app: "jmeter"
  type: "ClusterIP"
